"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h_^z&anzwca8yfou25ajm$pqc6ouj90a6*9o@hs4jdzf#ay590'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*","127.0.0.1","localhost","edisalkes.herokuapp.com", "www.putraharyandaalkesindo.com", "putraharyandaalkesindo.com"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'src',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'src.context_processors.main_processor',
            ],
            'libraries':{
                'main_tags': 'templates.tags.main_tags',
            }
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'putrahar_edisalkes', # Databaes Name
        'USER': 'putrahar_admin_db', # User Name
        'PASSWORD': '4dm1n@edisalkes', #Password
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'default2': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'db_edisalkes', # Databaes Name
        'USER': 'postgres', # User Name
        'PASSWORD': 'qweasd', #Password
        'HOST': '127.0.0.1',
        'PORT': '5432',
    },
    'default3': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'd1k836o1s3lupo', # Databaes Name
        'USER': 'kivxmjqdsapwzz', # User Name
        'PASSWORD': 'b40b0ab361d874e4b4d2a98898fad749f07560865910e9b435cde898b24c9371', #Password
        'HOST': 'ec2-34-195-69-118.compute-1.amazonaws.com',
        'PORT': '5432',
    },
    'secondary': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

AUTH_USER_MODEL = 'src.User'
LOGIN_URL = '/staff/login/'

# STATIC_URL = '/static/'
# STATIC_URL = '/static/'
# STATICFILES_DIRS = [BASE_DIR+"/static/assets/"]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
 
# STATIC_ROOT = '/home/zainulxy/t2d.zainul.xyz/static/'
 
# MEDIA_ROOT = '/ImGrY/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),]

MEDIA_URL = 'uploads/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880 #5MB
