# Generated by Django 3.2.9 on 2022-10-02 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='no_purchase_order',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sales',
            name='nama_pic',
            field=models.ForeignKey(blank=True, db_column='nama_pic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_pic', to='src.lembaga'),
        ),
        migrations.AddField(
            model_name='sales',
            name='pic',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sales',
            name='surat_pesanan_instansi',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='dp',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
