# Generated by Django 3.2.9 on 2022-10-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beban',
            name='kode_beban',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
