# Generated by Django 3.2.9 on 2021-11-19 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_status', models.CharField(max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=191, unique=True)),
                ('transaction_date', models.DateTimeField()),
                ('vendor_name', models.CharField(blank=True, max_length=191, null=True)),
                ('total', models.FloatField()),
                ('tax', models.FloatField(default=0.1)),
                ('total_amount', models.FloatField()),
                ('dp', models.FloatField(blank=True, null=True)),
                ('sisa_pembayaran', models.FloatField()),
                ('receiver_name', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_created_sale_by', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_status', to='src.masterstatus')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_updated_sale_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=191)),
                ('product_name', models.CharField(max_length=191)),
                ('quantity', models.SmallIntegerField()),
                ('size', models.CharField(max_length=191)),
                ('unit_price', models.FloatField()),
                ('amount', models.FloatField()),
                ('ss', models.ForeignKey(db_column='sale_id', on_delete=django.db.models.deletion.CASCADE, related_name='has_sale_detail', to='src.sales')),
            ],
            options={
                'verbose_name_plural': 'Sale Detail',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=191)),
                ('transaction_date', models.DateTimeField()),
                ('vendor_name', models.CharField(blank=True, max_length=191, null=True)),
                ('total', models.FloatField()),
                ('tax', models.FloatField(default=0.1)),
                ('total_amount', models.FloatField()),
                ('dp', models.FloatField(blank=True, null=True)),
                ('sisa_pembayaran', models.FloatField()),
                ('receiver_name', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=191)),
                ('product_name', models.CharField(max_length=191)),
                ('quantity', models.SmallIntegerField()),
                ('size', models.CharField(max_length=191)),
                ('unit_price', models.FloatField()),
                ('amount', models.FloatField()),
                ('ps', models.ForeignKey(db_column='purchase_id', on_delete=django.db.models.deletion.CASCADE, related_name='has_purchase_detail', to='src.purchases')),
            ],
            options={
                'verbose_name_plural': 'Purchases Detail',
            },
        ),
    ]
