# Generated by Django 3.2.9 on 2021-11-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_masterstatus_purchasedetail_purchases_saledetail_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='tax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='tax',
            field=models.FloatField(),
        ),
    ]
