# Generated by Django 3.2.9 on 2022-10-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20221002_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembaga',
            name='pic',
            field=models.CharField(default='', max_length=255, verbose_name='Pic'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pic',
            field=models.CharField(default='', max_length=255, verbose_name='Pic'),
        ),
    ]
