# Generated by Django 3.2.9 on 2021-12-03 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20211119_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_status_detail', to='src.masterstatus'),
        ),
    ]
