# Generated by Django 3.2.9 on 2021-12-20 04:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_saledetail_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=191, verbose_name='Nama Karyawan')),
                ('hp', models.CharField(max_length=21, verbose_name='Nomor HP')),
                ('email', models.CharField(max_length=191, verbose_name='Email')),
                ('jabatan', models.CharField(max_length=191, verbose_name='Jabatan')),
                ('alamat', models.TextField(verbose_name='alamat')),
            ],
            options={
                'verbose_name_plural': 'Manajemen Karyawan',
            },
        ),
        migrations.CreateModel(
            name='Lembaga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('nama_lembaga', models.CharField(
                    max_length=191, verbose_name='Nama Lembaga/Instansi')),
                ('hp', models.CharField(max_length=21, verbose_name='Nomor HP')),
                ('email', models.CharField(max_length=191, verbose_name='Email')),
                ('alamat', models.TextField(verbose_name='Alamat')),
                ('nama_pic', models.CharField(verbose_name='Nama PIC', max_length=255)),
                ('hp_pic', models.CharField(max_length=21, verbose_name='Hp PIC')),
            ],
            options={
                'verbose_name_plural': 'Manajemen Lembaga/Instansi',
            },
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(
                    max_length=191, verbose_name='Nama Barang')),
                ('id_vendor', models.CharField(
                    max_length=21, verbose_name='ID Vendor')),
                ('harga_jual', models.FloatField(
                    blank=True, null=True, verbose_name='Harga Jual')),
                ('harga_beli', models.FloatField(
                    blank=True, null=True, verbose_name='Harga Beli')),
                ('tgl_terima_stok', models.DateTimeField(verbose_name='Tgl Terima Stok')),
                
            ],
            options={
                'verbose_name_plural': 'Manajemen Pelanggan',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('nama_vendor', models.CharField(
                    max_length=191, verbose_name='Nama Vendor')),
                ('hp', models.CharField(max_length=21, verbose_name='Nomor HP')),
                ('email', models.CharField(max_length=191, verbose_name='Email')),
                ('alamat', models.TextField(verbose_name='Alamat')),
                ('nama_pic', models.CharField(max_length=255, verbose_name='Nama PIC')),
                ('hp_pic', models.CharField(max_length=21, verbose_name='Nomor HP PIC')),
            ],
            options={
                'verbose_name_plural': 'Manajemen Vendor',
            },
        ),
    ]
