# Generated by Django 3.2.9 on 2021-12-20 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_karyawan_pelanggan_stok_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='KasKecil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tgl_pencatatan', models.DateTimeField(blank=True, null=True)),
                ('no_kas', models.CharField(max_length=20)),
                ('nama_karyawan', models.CharField(max_length=191)),
                ('nominal', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_created_kaskecil_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_updated_kaskecil_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kas Kecil',
            },
        ),
        migrations.CreateModel(
            name='KasKecilDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_kebutuhan', models.CharField(max_length=30)),
                ('jenis_kebutuhan', models.CharField(max_length=191)),
                ('quantity', models.SmallIntegerField()),
                ('unit_price', models.FloatField()),
                ('kk', models.ForeignKey(db_column='kaskecil_id', on_delete=django.db.models.deletion.CASCADE, related_name='has_kaskecil_detail', to='src.kaskecil')),
            ],
            options={
                'verbose_name_plural': 'Kas Kecil Detail',
            },
        ),
        migrations.CreateModel(
            name='KasBesar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tgl_pencatatan', models.DateTimeField(blank=True, null=True)),
                ('no_transaksi', models.CharField(max_length=20)),
                ('pengirim', models.CharField(max_length=191)),
                ('bank_pengirim', models.CharField(max_length=191)),
                ('nominal', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_created_kasbesar_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_updated_kasbesar_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kas Besar',
            },
        ),
    ]
