# Generated by Django 3.2.9 on 2022-10-02 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_remove_sales_nama_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='pic',
            field=models.ForeignKey(blank=True, db_column='pic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_pic', to='src.lembaga'),
        ),
    ]
