# Generated by Django 3.2.9 on 2021-12-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_kasbesar_kaskecil_kaskecildetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaskecildetail',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
