# Generated by Django 3.2.9 on 2022-10-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_alter_sales_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='dp_persen',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
