# Generated by Django 3.2.9 on 2021-12-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_kaskecildetail_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='stok',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
