# Generated by Django 3.2.9 on 2021-12-25 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_stok_stok'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stok',
            options={'verbose_name_plural': 'Manajemen Stok'},
        ),
        migrations.AlterField(
            model_name='stok',
            name='id_vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_vendor_id', to='src.vendor'),
        ),
    ]
