# Generated by Django 3.2.9 on 2022-10-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_auto_20221005_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kasbesar',
            name='jenis_kas',
            field=models.CharField(default='', max_length=20),
        ),
    ]
