# Generated by Django 3.2.9 on 2022-01-13 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_auto_20211225_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='pelanggan',
            field=models.ForeignKey(blank=True, db_column='pelanggan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_pelanggan', to='src.pelanggan'),
        ),
        migrations.AddField(
            model_name='stok',
            name='size',
            field=models.CharField(default='', max_length=191),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchases',
            name='vendor_name',
            field=models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_vendor', to='src.vendor'),
        ),
    ]
