# Generated by Django 3.2.9 on 2022-10-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_alter_kasbesar_jenis_kas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kasbesar',
            name='keterangan',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
