# Generated by Django 3.2.9 on 2022-01-13 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_auto_20220113_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='pelanggan',
        ),
    ]
