# Generated by Django 3.2.9 on 2022-01-13 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_remove_sales_pelanggan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='vendor_name',
            field=models.ForeignKey(blank=True, db_column='pelanggan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_pelanggan', to='src.pelanggan'),
        ),
    ]
