# Generated by Django 3.2.9 on 2022-01-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_alter_sales_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='product_code',
            field=models.CharField(default='', max_length=191, unique=True),
            preserve_default=False,
        ),
    ]
