# Generated by Django 3.2.9 on 2022-01-13 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_stok_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='product_name',
            field=models.ForeignKey(db_column='product_stok', on_delete=django.db.models.deletion.CASCADE, related_name='has_stok_ps', to='src.stok'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='product_name',
            field=models.ForeignKey(db_column='product_stok', on_delete=django.db.models.deletion.CASCADE, related_name='has_stok_sale', to='src.stok'),
        ),
    ]
