# Generated by Django 3.2.9 on 2022-01-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_auto_20220113_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='product_code',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='size',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='product_code',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='size',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
