# Generated by Django 3.2.9 on 2022-10-08 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_kasbesarkeluar_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaskecildetail',
            name='id_kebutuhan',
            field=models.ForeignKey(db_column='id_kebutuhan', on_delete=django.db.models.deletion.CASCADE, related_name='has_kebutuhan_detail', to='src.beban'),
        ),
    ]
