# Generated by Django 3.2.9 on 2022-01-13 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_auto_20220113_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='receiver_name',
            field=models.ForeignKey(blank=True, db_column='karyawan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_karyawan_ps', to='src.karyawan'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='receiver_name',
            field=models.ForeignKey(blank=True, db_column='karyawan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_karyawan_ss', to='src.karyawan'),
        ),
    ]
