# Generated by Django 3.2.9 on 2022-10-11 21:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_alter_kaskecildetail_id_kebutuhan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pic', models.CharField(max_length=191, verbose_name='pic')),
                ('id_lembaga', models.ForeignKey(blank=True, db_column='lembaga_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_lembaga_id', to='src.lembaga')),
            ],
            options={
                'verbose_name_plural': 'PIC',
            },
        ),
    ]
