# Generated by Django 3.2.9 on 2022-10-11 21:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0016_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembaga',
            name='id_pic',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.DeleteModel(
            name='PIC',
        ),
    ]
