# Generated by Django 3.2.9 on 2022-01-14 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0016_auto_20220113_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaskecil',
            name='nama_karyawan',
            field=models.ForeignKey(blank=True, db_column='karyawan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_karyawan', to='src.karyawan'),
        ),
    ]
