# Generated by Django 3.2.9 on 2022-07-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_alter_kaskecil_nama_karyawan'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='nomor_surat_jalan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='ongkos_kirim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='overdue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
