# Generated by Django 3.2.9 on 2022-10-11 21:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_auto_20221011_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pic', models.CharField(max_length=191, verbose_name='pic')),
            ],
            options={
                'verbose_name_plural': 'PIC',
            },
        ),
        migrations.RemoveField(
            model_name='lembaga',
            name='id_pic',
        ),
    ]
