# Generated by Django 3.2.9 on 2022-07-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0018_auto_20220708_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='tax_persen',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
