# Generated by Django 3.2.9 on 2022-10-11 22:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0018_auto_20221011_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalKasBesarKeluar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_kas', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Total Kas Keluar',
            },
        ),
    ]
