# Generated by Django 3.2.9 on 2022-07-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0019_purchases_tax_persen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='overdue',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
