# Generated by Django 3.2.9 on 2022-10-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0019_totalkasbesarkeluar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalkasbesarkeluar',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
