# Generated by Django 3.2.9 on 2022-10-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0020_alter_totalkasbesarkeluar_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalKasBesarKeluar',
        ),
        migrations.AddField(
            model_name='kasbesarkeluar',
            name='total_kas',
            field=models.FloatField(default=0),
        ),
    ]
