# Generated by Django 3.2.9 on 2022-10-12 02:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0021_auto_20221012_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalKasBesarKeluar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_kas', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Total Kas Besar Keluar',
            },
        ),
        migrations.RemoveField(
            model_name='kasbesarkeluar',
            name='total_kas',
        ),
    ]
