# Generated by Django 3.2.9 on 2022-07-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0021_auto_20220711_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPersen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_persen', models.CharField(blank=True, max_length=100, null=True)),
                ('angka', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Manajemen Persentase',
            },
        ),
    ]
