# Generated by Django 3.2.9 on 2022-09-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0022_masterpersen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterstatus',
            options={'verbose_name_plural': 'Master Status'},
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='alamat',
            field=models.TextField(verbose_name='Alamat'),
        ),
    ]
