# Generated by Django 3.2.9 on 2022-10-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0023_alter_totalkasbesarkeluar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalkasbesarkeluar',
            name='total_kas',
            field=models.CharField(max_length=255),
        ),
    ]
