# Generated by Django 3.2.9 on 2022-10-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0024_alter_totalkasbesarkeluar_total_kas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='pic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
