# Generated by Django 3.2.9 on 2022-10-13 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0026_alter_totalkasbesarkeluar_total_kas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PIC',
        ),
    ]
